Account for secret.created possibly being None
current code will simply fail with
NameError: name 'created' is not defined

Change-Id: Idb907edf84900c517f538d2bfc9f334244368067