Fix AttributeError caused by mocked RequestContext
Fix the following errors detected in unit tests.

- AttributeError: Mock object has no attribute 'project_id'
- AttributeError: Mock object has no attribute 'project_domain_id'

Change-Id: I6c9d3123c42fa56498e377e038dea2f0a5132d9e